# Generated by Django 3.0.3 on 2020-05-02 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_totalPrice', models.IntegerField(default=0, verbose_name='Total Price')),
                ('order_deliveryFee', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Delivery Fee')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of order')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'OOut for delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30, null=True, verbose_name='Product Name')),
                ('prod_cat', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=30, null=True, verbose_name='Product Category')),
                ('prod_qty', models.IntegerField(default=0, null=True, verbose_name='Product Quantity')),
                ('prod_price', models.FloatField(null=True, verbose_name='Product Price (in LL)')),
                ('prod_bestSeller', models.CharField(default='Unknown Yet', max_length=30, null=True, verbose_name='Product Best Seller')),
                ('prod_dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
