# Generated by Django 3.0.3 on 2020-05-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200503_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_email',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
