# Generated by Django 3.0.3 on 2020-05-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200503_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(max_length=100, null=True, verbose_name='Note'),
        ),
    ]
