# Generated by Django 3.0.3 on 2020-05-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_cust_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
