# Generated by Django 3.0.5 on 2020-05-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_cat',
            field=models.CharField(choices=[('Baked Goods', 'Baked Goods'), ('Bread', 'Bread'), ('Breakfast', 'Breakfast'), ('Candy', 'Candy'), ('Care Products', 'Care Products'), ('Chips', 'Chips'), ('Chocolate', 'Chocolate'), ('Cookies', 'Cookies'), ('Dairy', 'Dairy'), ('Drinks', 'Drinks'), ('Dry Goods', 'Dry Goods'), ('Healthy Snacks', 'Healthy Snacks'), ('Ice Cream', 'Ice Cream'), ('Spreads', 'Spreads')], max_length=30, null=True, verbose_name='Product Category'),
        ),
    ]
