# Generated by Django 3.0.3 on 2020-05-04 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20200504_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=30, null=True, verbose_name='Supplier Name')),
                ('supp_phone', models.CharField(max_length=20, null=True, verbose_name='Supplier Phone Number')),
                ('supp_date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('supp_email', models.CharField(max_length=30, null=True, verbose_name='Supplier Email')),
                ('supp_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
