# Generated by Django 3.0.3 on 2020-05-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supp_user',
        ),
    ]
